#!/usr/bin/env node

const http = require('node:http');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const HOST = process.env.PI5_DASHBOARD_API_HOST || '127.0.0.1';
const PORT = Number.parseInt(process.env.PI5_DASHBOARD_API_PORT || '8092', 10);
const ENV_PATH = process.env.PI5_DASHBOARD_ENV_PATH || path.join(os.homedir(), '.pi5-dashboard.keys.env');

function nowIso() {
  return new Date().toISOString();
}

function sendJson(res, code, obj) {
  const body = JSON.stringify(obj);
  res.writeHead(code, {
    'Content-Type': 'application/json; charset=utf-8',
    'Cache-Control': 'no-store',
    'Content-Length': Buffer.byteLength(body)
  });
  res.end(body);
}

function readBody(req, limitBytes = 256 * 1024) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    let total = 0;
    req.on('data', (c) => {
      total += c.length;
      if (total > limitBytes) {
        reject(new Error('body too large'));
        req.destroy();
        return;
      }
      chunks.push(c);
    });
    req.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
    req.on('error', reject);
  });
}

function isValidKeyName(name) {
  return /^[A-Z_][A-Z0-9_]*$/.test(name);
}

function decodeShellValue(raw) {
  // Accept: VALUE, 'VALUE', "VALUE".
  const v = raw.trim();
  if (!v) return '';
  if (v.startsWith("'") && v.endsWith("'")) {
    return v.slice(1, -1);
  }
  if (v.startsWith('"') && v.endsWith('"')) {
    const inner = v.slice(1, -1);
    return inner
      .replace(/\\n/g, '\n')
      .replace(/\\r/g, '\r')
      .replace(/\\t/g, '\t')
      .replace(/\\"/g, '"')
      .replace(/\\\\/g, '\\');
  }
  return v;
}

function encodeShellValue(value) {
  // Single-quote for safe `source` usage. Escape single quotes via: 'foo'\''bar'
  const s = String(value);
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

function parseEnvFile(text) {
  const out = {};
  const lines = String(text || '').split(/\r?\n/);
  for (const line of lines) {
    const raw = line.trim();
    if (!raw) continue;
    if (raw.startsWith('#')) continue;

    const m = raw.match(/^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
    if (!m) continue;

    const key = m[1];
    let value = m[2] ?? '';
    // Strip inline comments only when unquoted.
    if (!(value.startsWith("'") || value.startsWith('"'))) {
      const hash = value.indexOf('#');
      if (hash !== -1) value = value.slice(0, hash);
    }

    out[key] = decodeShellValue(value);
  }
  return out;
}

function readEnvMap() {
  try {
    const raw = fs.readFileSync(ENV_PATH, 'utf8');
    return parseEnvFile(raw);
  } catch (e) {
    if (e && e.code === 'ENOENT') return {};
    throw e;
  }
}

function writeEnvMapAtomic(map) {
  const dir = path.dirname(ENV_PATH);
  fs.mkdirSync(dir, { recursive: true, mode: 0o700 });

  const keys = Object.keys(map).sort((a, b) => a.localeCompare(b));
  const lines = [];
  lines.push(`# Generated by pi5-dashboard-api at ${nowIso()}`);
  lines.push('# Contains secrets. Keep this file private.');
  for (const k of keys) {
    const v = map[k];
    if (v == null) continue;
    const vv = String(v);
    if (!vv) continue;
    lines.push(`export ${k}=${encodeShellValue(vv)}`);
  }
  const body = lines.join('\n') + '\n';

  const tmp = `${ENV_PATH}.tmp.${process.pid}`;
  fs.writeFileSync(tmp, body, { encoding: 'utf8', mode: 0o600 });
  fs.renameSync(tmp, ENV_PATH);
  fs.chmodSync(ENV_PATH, 0o600);
}

function jsonError(res, code, msg) {
  sendJson(res, code, { ok: false, error: msg });
}

const server = http.createServer(async (req, res) => {
  try {
    const url = new URL(req.url || '/', `http://${req.headers.host || 'localhost'}`);

    if (req.method === 'GET' && url.pathname === '/api/health') {
      sendJson(res, 200, { ok: true, now: nowIso() });
      return;
    }

    if (req.method === 'GET' && url.pathname === '/api/config/env') {
      const values = readEnvMap();
      sendJson(res, 200, { ok: true, values, updatedAt: nowIso(), envPath: ENV_PATH });
      return;
    }

    if (req.method === 'POST' && url.pathname === '/api/config/env/update') {
      const raw = await readBody(req);
      let body;
      try {
        body = raw ? JSON.parse(raw) : {};
      } catch {
        jsonError(res, 400, 'invalid json');
        return;
      }

      const setObj = body && typeof body === 'object' ? body.set : null;
      if (!setObj || typeof setObj !== 'object') {
        jsonError(res, 400, 'missing set');
        return;
      }

      const current = readEnvMap();
      const changed = [];

      for (const [k, v] of Object.entries(setObj)) {
        if (!isValidKeyName(k)) continue;

        if (v == null) {
          if (k in current) {
            delete current[k];
            changed.push(k);
          }
          continue;
        }

        if (typeof v !== 'string') continue;
        const vv = v.trim();
        if (!vv) continue;
        current[k] = vv;
        changed.push(k);
      }

      writeEnvMapAtomic(current);
      sendJson(res, 200, { ok: true, changed: Array.from(new Set(changed)).sort() });
      return;
    }

    jsonError(res, 404, 'not found');
  } catch (e) {
    jsonError(res, 500, e instanceof Error ? e.message : String(e));
  }
});

server.listen(PORT, HOST, () => {
  // Avoid logging secrets.
  console.log(`[pi5-dashboard-api] listening on http://${HOST}:${PORT} (env: ${ENV_PATH})`);
});
